apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-clusterip
spec:
  type: ClusterIP
  ports:
    - name: http-api
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }} 
      protocol: TCP
  selector:
    component: {{ .Values.api.components }}
